-- MySQL Script generated by MySQL Workbench
-- 01/30/16 23:18:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Aurora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Aurora` ;

-- -----------------------------------------------------
-- Schema Aurora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aurora` DEFAULT CHARACTER SET utf8 ;
USE `Aurora` ;

-- -----------------------------------------------------
-- Table `Aurora`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`user` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(55) NULL,
  `email` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL,
  `passwd` VARCHAR(512) NULL,
  `energie` INT NULL DEFAULT 100,
  `maxenergie` INT NULL DEFAULT 100,
  `rang` INT NULL DEFAULT 0,
  `money` INT NULL DEFAULT 500,
  `points` INT NULL DEFAULT 0,
  `idvaisseau` INT NOT NULL DEFAULT 0,
  `salt` VARCHAR(256) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`connecté`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`connecté` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`connecté` (
  `lastco` TIMESTAMP NULL,
  `iduser` INT NOT NULL,
  INDEX `fk_connecté_user_idx` (`iduser` ASC),
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_connecté_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `Aurora`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`item` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`item` (
  `idiitem` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(65) NULL,
  `desc` LONGTEXT NULL,
  `prix` INT NULL,
  `image` VARCHAR(255) NULL,
  `spec` VARCHAR(45) NULL,
  `bonus` INT NULL,
  PRIMARY KEY (`idiitem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`vaisseau`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`vaisseau` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`vaisseau` (
  `idvaisseau` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(65) NULL,
  `desc` LONGTEXT NULL,
  `pv` INT NULL,
  `attaque` INT NULL,
  `defense` INT NULL,
  `xp` INT NULL DEFAULT 0,
  `nextlevel` INT NULL DEFAULT 100,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `iduser` INT NOT NULL,
  `level` INT NULL DEFAULT 1,
  PRIMARY KEY (`idvaisseau`),
  INDEX `fk_vaisseau_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_vaisseau_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Aurora`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`equipement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`equipement` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`equipement` (
  `iduser` INT NOT NULL,
  `idiitem` INT NOT NULL,
  INDEX `fk_equipement_user1_idx` (`iduser` ASC),
  INDEX `fk_equipement_item1_idx` (`idiitem` ASC),
  PRIMARY KEY (`iduser`, `idiitem`),
  CONSTRAINT `fk_equipement_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Aurora`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipement_item1`
    FOREIGN KEY (`idiitem`)
    REFERENCES `Aurora`.`item` (`idiitem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`mission` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`mission` (
  `idmission` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(65) NULL,
  `niveau` INT NULL,
  `or` INT NULL,
  `xp` INT NULL,
  `desc` LONGTEXT NULL,
  `image` VARCHAR(255) NULL,
  `energie` INT NULL,
  PRIMARY KEY (`idmission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`effectue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`effectue` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`effectue` (
  `iduser` INT NOT NULL,
  `idmission` INT NOT NULL,
  INDEX `fk_effectue_user1_idx` (`iduser` ASC),
  INDEX `fk_effectue_mission1_idx` (`idmission` ASC),
  PRIMARY KEY (`idmission`, `iduser`),
  CONSTRAINT `fk_effectue_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Aurora`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effectue_mission1`
    FOREIGN KEY (`idmission`)
    REFERENCES `Aurora`.`mission` (`idmission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`spaceship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`spaceship` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`spaceship` (
  `idspaceship` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(65) NULL,
  `desc` LONGTEXT NULL,
  `pv` INT NULL,
  `attaque` INT NULL,
  `defense` INT NULL,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `prix` INT NULL,
  `xp` INT NULL DEFAULT 0,
  `nextlevel` INT NULL DEFAULT 100,
  PRIMARY KEY (`idspaceship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`spaceship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`spaceship` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`spaceship` (
  `idspaceship` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(65) NULL,
  `desc` LONGTEXT NULL,
  `pv` INT NULL,
  `attaque` INT NULL,
  `defense` INT NULL,
  `type` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `prix` INT NULL,
  `xp` INT NULL DEFAULT 0,
  `nextlevel` INT NULL DEFAULT 100,
  PRIMARY KEY (`idspaceship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`IA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`IA` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`IA` (
  `idIA` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `pv` INT NULL,
  `attaque` INT NULL,
  `defense` INT NULL,
  `image` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`ennemi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`ennemi` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`ennemi` (
  `idIA` INT NOT NULL,
  `idmission` INT NOT NULL,
  INDEX `fk_ennemi_IA1_idx` (`idIA` ASC),
  INDEX `fk_ennemi_mission1_idx` (`idmission` ASC),
  CONSTRAINT `fk_ennemi_IA1`
    FOREIGN KEY (`idIA`)
    REFERENCES `Aurora`.`IA` (`idIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ennemi_mission1`
    FOREIGN KEY (`idmission`)
    REFERENCES `Aurora`.`mission` (`idmission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aurora`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aurora`.`news` ;

CREATE TABLE IF NOT EXISTS `Aurora`.`news` (
  `idnews` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(150) NULL,
  `desc` LONGTEXT NULL,
  `image` VARCHAR(255) NULL,
  `date` TIMESTAMP NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idnews`),
  INDEX `fk_news_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `Aurora`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
